public class PrescriptionTriggerHandler {

    public static void blockDupeRx(List<Prescription__c> newList) {
        // Have list of new prescription sObjects.
        // get patient names
        // get

        // for(Prescription__c rx : newList) {
        //     if (pt.size() > 0) {
        //         rx.addError('Patient already has the same prescription.');
        //     }
        // }
    }

}
 